// Generated by 'unplugin-auto-import'
export {}
declare global {
  const describe: typeof import('vitest')['describe']
  const expect: typeof import('vitest')['expect']
  const it: typeof import('vitest')['it']
}
